version: '2'
services:
    jblogapp-app:
        image: jblogapp
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://jblogapp-postgresql:5432/jblogapp
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    jblogapp-postgresql:
        extends:
            file: postgresql.yml
            service: jblogapp-postgresql
